import logging
import json
import sys
import traceback
from datetime import datetime, timezone
from typing import Optional
from app.config import get_settings


# TODO: Review this logging config. It was generated by Cursor entirely.
class JsonLineFormatter(logging.Formatter):
    """A minimal JSON formatter for stdout log aggregation.

    Outputs one JSON object per line.
    """

    _RESERVED_ATTRS = {
        "args",
        "asctime",
        "created",
        "exc_info",
        "exc_text",
        "filename",
        "funcName",
        "levelname",
        "levelno",
        "lineno",
        "module",
        "msecs",
        "message",
        "msg",
        "name",
        "pathname",
        "process",
        "processName",
        "relativeCreated",
        "stack_info",
        "thread",
        "threadName",
    }

    def format(self, record: logging.LogRecord) -> str:
        payload: dict[str, object] = {
            "timestamp": datetime.fromtimestamp(
                record.created, tz=timezone.utc
            ).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }

        # Helpful structured-ish context without being too noisy
        payload.update(
            {
                "module": record.module,
                "func": record.funcName,
                "line": record.lineno,
            }
        )

        if record.exc_info:
            payload["exception"] = "".join(
                traceback.format_exception(*record.exc_info)
            ).strip()

        # Include extra fields (e.g. logger.info("...", extra={"foo": "bar"}))
        for key, value in record.__dict__.items():
            if key in self._RESERVED_ATTRS or key.startswith("_"):
                continue
            try:
                json.dumps(value)
                payload[key] = value
            except TypeError:
                payload[key] = str(value)

        return json.dumps(payload, ensure_ascii=False)


class LoggingConfig:
    _instance: Optional["LoggingConfig"] = None
    _initialized: bool = False

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self):
        if not self._initialized:
            self._settings = get_settings()
            self._configure_logging()
            self._initialized = True

    def _configure_logging(self):
        """Configure logging based on settings."""
        log_level = getattr(logging, self._settings.log_level.upper())
        log_format = (self._settings.log_format or "text").strip().lower()
        formatter: logging.Formatter
        if log_format == "json":
            formatter = JsonLineFormatter()
        else:
            formatter = logging.Formatter(
                "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            )

        # Configure root logger
        root_logger = logging.getLogger()
        root_logger.setLevel(log_level)
        if not root_logger.handlers:
            root_handler = logging.StreamHandler(stream=sys.stdout)
            root_handler.setFormatter(formatter)
            root_logger.addHandler(root_handler)

        # Configure specific loggers
        loggers = {
            "uvicorn": log_level,
            "uvicorn.error": log_level,
            "uvicorn.access": log_level,
            "app": log_level,
            "fastapi": log_level,
            # Set third-party loggers to higher levels
            "httpx": logging.WARNING,
            "httpcore": logging.WARNING,
            "openai": logging.WARNING,
            "urllib3": logging.WARNING,
            "sqlalchemy": logging.WARNING,
            "llama_index": logging.WARNING,
        }

        for logger_name, level in loggers.items():
            logger = logging.getLogger(logger_name)
            logger.setLevel(level)
            # Prevent propagation to root logger to avoid duplicate logs
            logger.propagate = False

            # Add handler if none exists
            if not logger.handlers:
                handler = logging.StreamHandler(stream=sys.stdout)
                handler.setFormatter(formatter)
                logger.addHandler(handler)
            else:
                # If uvicorn (or another lib) already installed handlers,
                # override their formatter to respect LOG_FORMAT.
                for handler in logger.handlers:
                    handler.setFormatter(formatter)

    @property
    def logger(self) -> logging.Logger:
        """Get a logger instance with the configured settings."""
        return logging.getLogger("uvicorn")

    def get_logger(self, name: str) -> logging.Logger:
        """Get a logger instance with the given name."""
        return logging.getLogger(name)


def get_logger(name: str = "uvicorn") -> logging.Logger:
    """Get a logger instance with the given name."""
    return LoggingConfig().get_logger(name)
